version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
# artifacts:
#   files:
#     - location
#     - location
  discard-paths: yes
  # base-directory: location
cache:
  paths:
    - node_modules
